# publish-issues.ps1 - Publish issues from SSOT to GitHub with update-in-place Task Links

param(
    [Parameter(Mandatory = $true)]
    [string]$RepoOwner,

    [Parameter(Mandatory = $true)]
    [string]$RepoName,

    [Parameter(Mandatory = $true)]
    [string]$IssuesDir,

    [switch]$DryRun,

    [ValidateSet('append', 'update')]
    [string]$TaskLinksWriteMode = 'update'
)

$ErrorActionPreference = 'Stop'

$Marker = '<!-- TASK_LINKS_AUTOGEN v1 -->'
$TaskLinksHeader = @"
$Marker

## Task Links
"@

function Get-SpecIssueNumber {
    param(
        [string]$IssuesDir,
        [string]$IssueFile
    )

    $content = Get-Content -Path $IssueFile -Raw
    if ($content -match 'Spec Issue:\s*#(\d+)') {
        return $matches[1]
    }
    return $null
}

function Get-SpecComments {
    param(
        [string]$RepoOwner,
        [string]$RepoName,
        [string]$IssueNumber
    )

    $apiUrl = "repos/$RepoOwner/$RepoName/issues/$IssueNumber/comments"
    $result = & gh api --paginate $apiUrl 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to fetch comments: $result"
        return $null
    }
    return $result | ConvertFrom-Json
}

function Find-AutogenTaskLinksComment {
    param(
        [object[]]$Comments,
        [string]$Marker
    )

    $markerComments = @($Comments | Where-Object { $_.body -like "*$Marker*" })

    if ($markerComments.Count -eq 0) {
        return $null
    }

    if ($markerComments.Count -gt 1) {
        Write-Warning "Found $($markerComments.Count) marker comments (IDs: $($markerComments.id -join ', ')). Will update the newest one."
    }

    return $markerComments | Sort-Object -Property created_at -Descending | Select-Object -First 1
}

function Build-TaskLinksBody {
    param(
        [string]$IssuesDir,
        [string]$SpecIssueNumber,
        [string]$Marker
    )

    $taskFiles = Get-ChildItem -Path $IssuesDir -Filter 'task-*.md' -File | Sort-Object Name

    if ($taskFiles.Count -eq 0) {
        return $null
    }

    $links = @()
    foreach ($taskFile in $taskFiles) {
        $taskNumber = $taskFile.Name -replace 'task-(\d+)\.md', '$1'
        $links += "- Task #${taskNumber}"
    }

    if ($links.Count -eq 0) {
        return $null
    }

    $body = "$Marker`n`n## Task Links`n`n"
    $body += $links -join "`n"
    $body += "`n`n*Auto-generated by publish-issues.ps1*"

    return $body
}

function Update-Or-Create-TaskLinksComment {
    param(
        [string]$RepoOwner,
        [string]$RepoName,
        [string]$IssueNumber,
        [string]$Body,
        [object]$ExistingComment,
        [switch]$DryRun
    )

    if ($ExistingComment) {
        if ($ExistingComment.body -eq $Body) {
            Write-Host "Task Links comment already up-to-date (Comment ID: $($ExistingComment.id)). Skipping."
            return $true
        }

        if ($DryRun) {
            Write-Host "[DryRun] Would update Task Links comment (Comment ID: $($ExistingComment.id))."
            return $true
        }

        $apiUrl = "repos/$RepoOwner/$RepoName/issues/comments/$($ExistingComment.id)"
        $patchBody = $Body | ConvertTo-Json
        $result = & gh api -X PATCH $apiUrl -f body=$patchBody 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to update comment: $result"
            return $false
        }

        Write-Host "Task Links comment updated (Comment ID: $($ExistingComment.id))."
        return $true
    } else {
        if ($DryRun) {
            Write-Host "[DryRun] Would create Task Links comment."
            return $true
        }

        $result = & gh issue comment $IssueNumber --repo "$RepoOwner/$RepoName" --body $Body 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to create comment: $result"
            return $false
        }

        Write-Host "Task Links comment created."
        return $true
    }
}

function Publish-SpecIssues {
    param(
        [string]$RepoOwner,
        [string]$RepoName,
        [string]$IssuesDir,
        [string]$TaskLinksWriteMode,
        [switch]$DryRun
    )

    $specFiles = Get-ChildItem -Path $IssuesDir -Filter 'spec-*.md' -File | Sort-Object Name

    if ($specFiles.Count -eq 0) {
        Write-Host "No spec files found in $IssuesDir"
        return
    }

    foreach ($specFile in $specFiles) {
        $specIssueNumber = Get-SpecIssueNumber -IssuesDir $IssuesDir -IssueFile $specFile.FullName

        if (-not $specIssueNumber) {
            Write-Host "No Spec Issue found for $($specFile.Name), skipping Task Links"
            continue
        }

        $taskLinksBody = Build-TaskLinksBody -IssuesDir $IssuesDir -SpecIssueNumber $specIssueNumber -Marker $Marker

        if (-not $taskLinksBody) {
            Write-Host "No tasks found for Spec #${specIssueNumber}, skipping Task Links"
            continue
        }

        if ($TaskLinksWriteMode -eq 'update') {
            $comments = Get-SpecComments -RepoOwner $RepoOwner -RepoName $RepoName -IssueNumber $specIssueNumber

            if ($null -eq $comments) {
                Write-Warning "Failed to fetch comments for Spec #${specIssueNumber}, skipping Task Links"
                continue
            }

            $existingComment = Find-AutogenTaskLinksComment -Comments $comments -Marker $Marker
        } else {
            $existingComment = $null
        }

        Write-Host "Processing Task Links for Spec #${specIssueNumber}..."
        Update-Or-Create-TaskLinksComment -RepoOwner $RepoOwner -RepoName $RepoName -IssueNumber $specIssueNumber -Body $taskLinksBody -ExistingComment $existingComment -DryRun:$DryRun
    }
}

Publish-SpecIssues -RepoOwner $RepoOwner -RepoName $RepoName -IssuesDir $IssuesDir -TaskLinksWriteMode $TaskLinksWriteMode -DryRun:$DryRun
